### ISSUE TITLE
Publish to the plugins repo?

### ISSUE THREAD

**Issue by astubbs** [darthorimar/logseq-movies-plugin#2]

**Comment by darthorimar** [comment]
Hi @astubbs! Thank you for your interest in the plugin. The plugin is already in the marketplace with [logseq-movies](https://github.com/logseq/marketplace/blob/master/packages/logseq-movies/manifest.json) id.

**Comment by astubbs** [comment]
omgosh, I'm blind! I went through all the plugins and didn't notice it :) 

And holy cow, myanimelist.net looks amazing.

**Comment by astubbs** [comment]
omg you're on the Kotlin team! 😍 すごい !! ;)
